name: CI for API-GATEWAY

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Set up Go
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23.1  # Match your Go version

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Create .env file using GitHub secrets variables- to copy to container
    - name: Create .env file
      run: |
        echo "JWTKEY=${{ secrets.JWTKEY }}" >> .env
        echo "USERPORT=${{ secrets. }}" >> .env
        echo "ADMINPORT=${{ secrets.ADMINPORT }}" >> .env
        echo "APIPORT=${{ secrets.APIPORT }}" >> .env
        echo "CHATPORT=${{ secrets.CHATPORT }}" >> .env

    # Build and push Docker image
    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/api_gateway:v1.0 .
        docker push ${{ secrets.DOCKER_USERNAME }}/api_gateway:v1.0
